package com.enth.uitmedown.presentation;

import android.os.Bundle;
import android.widget.Button;
import android.widget.ImageView;
import android.widget.TextView;
import android.widget.Toast;
import androidx.appcompat.app.AppCompatActivity;
import com.bumptech.glide.Glide;
import com.enth.uitmedown.R;
import com.enth.uitmedown.model.Item;
import com.enth.uitmedown.model.Notification;
import com.enth.uitmedown.model.Transaction;
import com.enth.uitmedown.model.User;
import com.enth.uitmedown.remote.ApiUtils;
import com.enth.uitmedown.sharedpref.SharedPrefManager;
import retrofit2.Call;
import retrofit2.Callback;
import retrofit2.Response;

public class ItemDetailActivity extends AppCompatActivity {

    private Item item;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_item_detail);

        // 1. Get Item from Intent
        if (getIntent().getSerializableExtra("item") != null) {
            item = (Item) getIntent().getSerializableExtra("item");
        } else {
            Toast.makeText(this, "Error loading item", Toast.LENGTH_SHORT).show();
            finish();
            return;
        }

        // 2. Setup UI
        TextView tvTitle = findViewById(R.id.tvDetailTitle);
        TextView tvPrice = findViewById(R.id.tvDetailPrice);
        TextView tvDesc = findViewById(R.id.tvDetailDesc);
        ImageView imgDetail = findViewById(R.id.imgDetail);
        Button btnBuy = findViewById(R.id.btnRequestBuy);

        tvTitle.setText(item.getTitle());
        tvPrice.setText("RM " + item.getPrice());
        tvDesc.setText(item.getDescription());

        if (item.getImageUrl() != null) {
            Glide.with(this).load(item.getImageUrl()).into(imgDetail);
        }

        // 3. Buy Button Logic
        btnBuy.setOnClickListener(v -> {
            submitBuyRequest();
        });
    }

    private void submitBuyRequest() {
        SharedPrefManager spm = new SharedPrefManager(this);
        int myUserId = spm.getUser().getId();

        // Prevent buying your own item
        if (myUserId == item.getSellerId()) {
            Toast.makeText(this, "You cannot buy your own item!", Toast.LENGTH_SHORT).show();
            return;
        }

        // Create the Transaction Object
        Transaction newDeal = new Transaction();
        newDeal.setItemId(item.getItemId());
        newDeal.setBuyerId(myUserId);
        newDeal.setSellerId(item.getSellerId());
        newDeal.setAmount(item.getPrice());
        newDeal.setStatus("pending");

        // Send to Server
        ApiUtils.getTransactionService().createTransaction(spm.getUser().getToken(), newDeal).enqueue(new Callback<Transaction>() {
            @Override
            public void onResponse(Call<Transaction> call, Response<Transaction> response) {
                if (response.isSuccessful()) {
                    Toast.makeText(ItemDetailActivity.this, "Request Sent!", Toast.LENGTH_LONG).show();
                    //notification
                    // CAPTURE the created transaction (which now includes the ID generated by DB)
                    Transaction createdTransaction = response.body();

                    // Pass it to the notification function
                    createNotificationForSeller(createdTransaction);
                    finish(); // Go back to main menu
                } else {
                    Toast.makeText(ItemDetailActivity.this, "Failed: " + response.code(), Toast.LENGTH_SHORT).show();
                }
            }

            @Override
            public void onFailure(Call<Transaction> call, Throwable t) {
                Toast.makeText(ItemDetailActivity.this, "Network Error", Toast.LENGTH_SHORT).show();
            }
        });
    }

    private void createNotificationForSeller(Transaction transaction) {
        SharedPrefManager spm = new SharedPrefManager(this);
        User me = spm.getUser();

        Notification notif = new Notification();
        notif.setSenderId(me.getId());
        notif.setReceiverId(item.getSellerId());
        notif.setTitle("New Buy Request");

        notif.setEventId("BUY_REQUEST"); // Matches the ID in your event_types table
        notif.setTransactionId(transaction.getTransactionId()); // Link to the transaction we just made

        // We don't really care about the callback here. If it fails, it fails.
        ApiUtils.getNotificationService().createNotification(spm.getUser().getToken(), notif).enqueue(new Callback<Notification>() {
            @Override
            public void onResponse(Call<Notification> call, Response<Notification> response) {
                // Optional logging
            }
            @Override
            public void onFailure(Call<Notification> call, Throwable t) {
                // Optional logging
            }
        });
    }
}